### ISSUE TITLE
Authentification with rollers

### ISSUE THREAD

**Issue by thebestgin** [SaladTechnologies/supertokens-dotnet#8]
Thank you for the repo. 

It it also possible to work out of the box with: [Authorize(Roles = "Administrator")]

**Comment by seniorquico** [comment]
Hi, @thebestgin! This SDK provides the backend implementation for SuperTokens-based authentication, e.g. for a frontend using [supertokens-website](https://www.npmjs.com/package/supertokens-website). It does not provide authorization primitives out of the box. However, this is due to ASP.NET Core's design. ASP.NET Core separates the authentication & authorization into two separate stages in the request pipeline. For reference:

- [Authentication](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-7.0)
- [Authorization](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/introduction?view=aspnetcore-7.0)

Notably, we use many authorization policies and annotate our controllers with the `[Authorize]` attribute all building on top of the SuperTokens authentication provided by this SDK. I don't see anything needed in this SDK to power a scenario as suggested.
